# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  2d_gravity_sim_config = debug

else ifeq ($(config),release)
  2d_gravity_sim_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := 2d_gravity_sim

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

2d_gravity_sim:
ifneq (,$(2d_gravity_sim_config))
	@echo "==== Building 2d_gravity_sim ($(2d_gravity_sim_config)) ===="
	@${MAKE} --no-print-directory -C . -f 2d_gravity_sim.make config=$(2d_gravity_sim_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f 2d_gravity_sim.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   2d_gravity_sim"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"