# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  gigafry_bot_config = debug

else ifeq ($(config),release)
  gigafry_bot_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := gigafry_bot

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

gigafry_bot:
ifneq (,$(gigafry_bot_config))
	@echo "==== Building gigafry_bot ($(gigafry_bot_config)) ===="
	@${MAKE} --no-print-directory -C . -f gigafry_bot.make config=$(gigafry_bot_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f gigafry_bot.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   gigafry_bot"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"